#!/usr/bin/env python

from __future__ import print_function

import os
import sys
import datetime

try:
    # newer obspy
    from obspy.clients.earthworm import Client
    from obspy import UTCDateTime
except:
    # older obspy
    from obspy.earthworm import Client
    from obspy.core import UTCDateTime



def usage(args):
    text = """
            Usage: {} hostname port starttime duration station_code

            where:
                 hostname: hostname or IP of earthworm wave_serverV or winston
                 port: port number of earthworm wave_serverV or winston
                 starttime: start of waveform, given as YYYYMMDDHHMMSS (year,month,day,hour,min,sec)
                 duration: length of waveform in seconds
                 station_code: name of station, e.g. TTES
            You provided: {}
            """.format(os.path.basename(args[0]),args[1:])
    print(text)
    return

if __name__ == "__main__":
    
    if len(sys.argv) != 6:
        usage(sys.argv)
        sys.exit(1)

    [host,port,starttime,duration,station] = sys.argv[1:]
    port = int(port)
    starttime = UTCDateTime(starttime)
    endtime = starttime + datetime.timedelta(seconds=float(duration))
    client = Client(host,port,timeout=5)

    # first, check if there are any data for this station in this waveserver
    availability = client.get_availability(station=station)
    if len(availability) == 0:
        print("No data for {} in {}:{}".format(station,host,port))
        sys.exit(1)
    else:
        for net,sta,loc,chan,t1,t2 in availability: 
            print("Requesting {}.{}.{}.{} from {}:{} for {} to {}".format(net,sta,loc,chan,host,port,starttime,endtime))
            st = client.get_waveforms(net,sta,loc,chan,starttime,endtime)
            st.merge()
            
            # write to SAC files
            for tr in st:
                filename = "{}.{}.{}.{}.{}".format(starttime.strftime("%Y%m%d%H%M%S"),\
                 tr.stats.network,tr.stats.station,tr.stats.location,tr.stats.channel)
                tr.write(filename,format="SAC")
    print("Wrote {} SAC files".format(len(availability)))
    sys.exit(0)
